export const BLUR_DATA_GRAY =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkkAEAACIAHrTmiyAAAAAASUVORK5CYII=';

export const BLUR_DATA_URL = `data:image/png;base64,${BLUR_DATA_GRAY}`;
