// https://png-pixel.com
// blurDataURL - TRANSPARENT BASE64 PNG PIXEL
export const BLUR_DATA_GRAY =
  // // 000000, opacity: 0.11. mui skeleton 컬러.
  // 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkkAEAACIAHrTmiyAAAAAASUVORK5CYII=';
  // 0.05.
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk4AEAABIADmFSrv8AAAAASUVORK5CYII=';

export const BLUR_DATA_URL = `data:image/png;base64,${BLUR_DATA_GRAY}`;
